routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::impersonate();

Route::get('/', function () {
//    return view('welcome');
    return view('coming-soon');
});

Route::get('/test', function () {
//    return view('welcome');
    return view('productlisting');
});




Route::get('cart', [\App\Http\Controllers\AdminDashboardController::class, 'cart'])->name('cart');

Route::get('add-to-cart/{id}', [\App\Http\Controllers\AdminDashboardController::class, 'addToCart'])->name('add.to.cart');

Route::Post('add-to-cart', [\App\Http\Controllers\AdminDashboardController::class, 'addToCartAjax'])->name('add.to.carts');

Route::patch('update-cart', [\App\Http\Controllers\AdminDashboardController::class, 'updateCart'])->name('update.cart');

Route::delete('remove-from-cart', [\App\Http\Controllers\AdminDashboardController::class, 'removeCart'])->name('remove.from.cart');

Route::get('checkout', [\App\Http\Controllers\AdminDashboardController::class, 'checkout']);
Route::post('create_order', [\App\Http\Controllers\ClubController::class, 'createOrder']);


Route::get('INSTAKTER', [\App\Http\Controllers\AdminDashboardController::class, 'productsVendor'])->name('productsVendor');

Route::get('INSTAKTER/{id}', [\App\Http\Controllers\AdminDashboardController::class, 'vendorLists'])->name('vendorLists');

Route::get('INSTAKTER/{id}/{categoryid}',[\App\Http\Controllers\AdminDashboardController::class, 'vendorLists2'])->name('vendorLists2');

Route::POST('productData', [\App\Http\Controllers\AdminDashboardController::class, 'productData'])->name('productData');
 
//Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//    return view('dashboard');
//})->name('dashboard');

//Route::middleware(['auth:sanctum', 'verified'])->group(['prefix' => 'admin'], function () {
//    Route::get('/', [\App\Http\Controllers\AdminDashboardController::class, 'index'])->name('admin');
//});

    Route::group(['middleware' => 'auth:admin', 'prefix'=> 'admin', 'as' => 'admin.'], function() {
        Route::get('dashboard', [\App\Http\Controllers\AdminDashboardController::class, 'index'])->name('dashboard');
        Route::post('loginAsVendor', [\App\Http\Controllers\AdminDashboardController::class, 'loginAsVendor'])->name('loginAsVendor');

        Route::get('vendorsList', [\App\Http\Controllers\AdminDashboardController::class, 'vendorsList'])->name('vendorsList');

        Route::get('customersList', [\App\Http\Controllers\AdminDashboardController::class, 'customersList'])->name('customersList');


        Route::get('ordersList', [\App\Http\Controllers\AdminDashboardController::class, 'ordersList'])->name('ordersList');


        //categories
        Route::get('categories', [\App\Http\Controllers\CategoryController::class, 'categoryList'])->name('categories');
        Route::get('admin/removeCategory', [\App\Http\Controllers\CategoryController::class, 'removeCategory'])->name('removeCategory');
        Route::get('admin/editCategory', [\App\Http\Controllers\CategoryController::class, 'showCategory'])->name('editCategory');
        Route::post('Category', [\App\Http\Controllers\CategoryController::class, 'storeCategory'])->name('Category');



        //   Route::get('productsList/{id?}', [\App\Http\Controllers\AdminDashboardController::class, 'productsList'])->name('productsList');
        Route::get('productsList', [\App\Http\Controllers\AdminDashboardController::class, 'productsList'])->name('productsList');
        Route::get('productsCreate', [\App\Http\Controllers\AdminDashboardController::class, 'productsCreate'])->name('productsCreate');
        Route::post('productADD', [\App\Http\Controllers\AdminDashboardController::class, 'productADD'])->name('productADD');
        Route::get('productView/{id}', [\App\Http\Controllers\AdminDashboardController::class, 'productView'])->name('productView');
        Route::post('productUpdate', [\App\Http\Controllers\AdminDashboardController::class, 'productUpdate'])->name('productUpdate');
        Route::post('productDelete', [\App\Http\Controllers\AdminDashboardController::class, 'productDelete'])->name('productDelete');

        Route::get('delProducts', [\App\Http\Controllers\AdminDashboardController::class, 'Removeproducts'])->name('DelProducts');

        Route::get('CategoryList', [\App\Http\Controllers\AdminDashboardController::class, 'categoryList'])->name('CategoryList');
        Route::get('removeCategory', [\App\Http\Controllers\AdminDashboardController::class, 'removeCategory'])->name('removeCategory');
        Route::get('editCategory', [\App\Http\Controllers\AdminDashboardController::class, 'showCategory'])->name('editCategory');
        Route::post('AddCategory', [\App\Http\Controllers\AdminDashboardController::class, 'storeCategory'])->name('AddCategory');

        Route::get('AdminProfile', [\App\Http\Controllers\AdminDashboardController::class, 'adminProfile'])->name('AdminProfile');
        Route::post('AdminProfileUpdate', [\App\Http\Controllers\AdminDashboardController::class, 'adminProfileUpdate'])->name('AdminProfileUpdate');

      //  Route::get('viewWidgets/{id?}', [\App\Http\Controllers\AdminDashboardController::class, 'viewWidgets'])->name('viewWidgets');
        Route::get('viewWidgets', [\App\Http\Controllers\AdminDashboardController::class, 'viewWidgets'])->name('viewWidgets');

     //   Route::get('viewMemberships/{id?}', [\App\Http\Controllers\AdminDashboardController::class, 'viewMemberships'])->name('viewMemberships');
        Route::get('viewMemberships', [\App\Http\Controllers\AdminDashboardController::class, 'viewMemberships'])->name('viewMemberships');

        Route::resource('defaultWidget', \App\Http\Controllers\DefaultWidgetController::class);

        Route::resource('defaultMemberships', \App\Http\Controllers\DefaultSubscriptionController::class);


    });



    Route::group(['middleware' => ['auth:vendor']], function() {

        Route::get('vendor/dashboard', [App\Http\Controllers\VendorDashboardController::class , 'index'])->name('vendor.dashboard');
        Route::resource('customers', \App\Http\Controllers\CustomersController::class);

        Route::resource('orders', \App\Http\Controllers\OrdersController::class);
        Route::resource('widget', \App\Http\Controllers\WidgetController::class);
        Route::resource('membership', \App\Http\Controllers\SubscriptionController::class);
        Route::resource('vendor', \App\Http\Controllers\VendorsController::class);
        Route::resource('products', \App\Http\Controllers\ProductsController::class);
        Route::get('updateSettings', [\App\Http\Controllers\VendorsController::class, 'updateSettings'])->name('updateSettings');
        Route::post('updateVendorSettings', [\App\Http\Controllers\VendorsController::class, 'updateVendorSettings'])->name('updateVendorSettings');

        Route::get('pluginSetting', [\App\Http\Controllers\VendorsController::class, 'pluginSetting']);
        Route::get('updateAccessToken/{id}', [\App\Http\Controllers\VendorsController::class, 'updateAccessToken']);
        Route::resource('myclub', \App\Http\Controllers\ClubController::class);

        Route::get('clubDetails', [\App\Http\Controllers\ClubController::class, 'index'])->name('ClubListing');



        //products vendor
        Route::resource('products', \App\Http\Controllers\ProductsController::class);
        Route::post('products/{product}', [\App\Http\Controllers\ProductsController::class, 'update'])->name('products.update');


        Route::get('customerDetails', [\App\Http\Controllers\CustomersController::class, 'index'])->name('CustomerListing');
        Route::get('customers/{id}', [\App\Http\Controllers\CustomersController::class, 'show'])->name('customers.view');

        Route::get('orderDetails', [\App\Http\Controllers\OrdersController::class, 'index'])->name('OrderListing');
        Route::get('orders/{id}', [\App\Http\Controllers\OrdersController::class, 'show'])->name('orders.view');




        Route::get('myclub/delete/{id}',[ \App\Http\Controllers\ClubController::class,'destroy']);
    });



Route::get('/admin/login', [\App\Http\Controllers\Auth\LoginController::class, 'showAdminLoginForm'])->name('admin/login');
Route::post('/admin/login', [\App\Http\Controllers\Auth\LoginController::class, 'userLogin'])->name('admin/login');
Route::post('/admin/logout', [\App\Http\Controllers\Auth\LogoutController::class, 'userLogout'])->name('admin/logout');


Route::get('/login', [\App\Http\Controllers\Auth\LoginController::class,'showVendorLogin'])->name('login');
Route::post('/login', [\App\Http\Controllers\Auth\LoginController::class,'vendorLogin'])->name('login');

Route::post('/registervendor', [\App\Http\Controllers\Auth\RegisterController::class,'registerVendor'])->name('registervendor');

Route::get('logout',[App\Http\Controllers\Auth\LogoutController::class , 'userLogout'])->name('logout');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/cart.blade.php
@extends('layouts.main')
@section('title', 'Category')
@section('head')
    @parent
    <!--  <link rel="stylesheet" href="./style.css">-->
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <title>INSTAKTER</title>
    <style>
        .bbb_deals_featured {
            width: 100%;
        }

        .bbb_deals {
            width: 100%;
            margin-right: 7%;
            padding-top: 80px;
            padding-left: 25px;
            padding-right: 25px;
            padding-bottom: 34px;
            box-shadow: 1px 1px 5px 1px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
            margin-top: 0px;
        }

        .bbb_deals_title {
            position: absolute;
            top: 10px;
            left: 22px;
            font-size: 18px;
            font-weight: 500;
            color: #000000;
        }

        .bbb_deals_slider_container {
            width: 100%;
        }

        .bbb_deals_item {
            width: 100% !important;
        }

        .bbb_deals_image {
            width: 100%;
        }

        .bbb_deals_image img {
            width: 100%;
        }

        .bbb_deals_content {
            margin-top: 33px;
        }

        .bbb_deals_item_category a {
            font-size: 14px;
            font-weight: 400;
            color: rgba(0, 0, 0, 0.5);
        }

        .bbb_deals_item_price_a {
            font-size: 14px;
            font-weight: 400;
            color: rgba(0, 0, 0, 0.6);
        }

        .bbb_deals_item_price_a strike {
            color: red;
        }

        .bbb_deals_item_name {
            font-size: 24px;
            font-weight: 400;
            color: #000000;
        }

        .bbb_deals_item_price {
            font-size: 24px;
            font-weight: 500;
            color: #6d6e73;
        }

        .available {
            margin-top: 19px;
        }

        .available_title {
            font-size: 16px;
            color: rgba(0, 0, 0, 0.5);
            font-weight: 400;
        }

        .available_title span {
            font-weight: 700;
        }

        @media only screen and (max-width: 991px) {
            .bbb_deals {
                width: 100%;
                margin-right: 0px;
            }
        }

        @media only screen and (max-width: 575px) {
            .bbb_deals {
                padding-left: 15px;
                padding-right: 15px;
            }

            .bbb_deals_title {
                left: 15px;
                font-size: 16px;
            }

            .bbb_deals_slider_nav_container {
                right: 5px;
            }

            .bbb_deals_item_name,
            .bbb_deals_item_price {
                font-size: 20px;
            }
        }
        footer{
            position: absolute;
            width: 100%;
            bottom: 0;
        }
    </style>

@endsection
@section('content')
    <br>
    @if(session('success'))

        <div class="container">
            <div class="col-md-12">
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            </div>

        </div>


    @endif
    <br>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">

                    <table id="cart" class="table table-hover table-condensed">
                        <thead>
                        <tr>
                            <th style="width:50%">Product</th>
                            <th style="width:10%">Price</th>
                            <th style="width:8%">Quantity</th>
                            <th style="width:22%" class="text-center">Subtotal</th>
                            <th style="width:10%"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @php $total = 0 @endphp

                        @if(session('cart'))

                            @foreach(session('cart') as $id => $details)

                                @php $total += $details['price'] * $details['quantity'] @endphp

                                <tr data-id="{{ $id }}">

                                    <td data-th="Product">

                                        <div class="row">

                                            <div class="col-sm-3 hidden-xs"><img src="{{ $details['image'] }}" width="100" height="100" class="img-responsive"/></div>

                                            <div class="col-sm-9">

                                                <h4 class="nomargin">{{ $details['name'] }}</h4>

                                            </div>

                                        </div>

                                    </td>

                                    <td data-th="Price">${{ $details['price'] }}</td>

                                    <td data-th="Quantity">

                                        <input type="number" min="1" value="{{ $details['quantity'] }}" class="form-control quantity update-cart" />

                                    </td>

                                    <td data-th="Subtotal" class="text-center">${{ $details['price'] * $details['quantity'] }}</td>

                                    <td class="actions" data-th="">

                                        <button class="btn btn-danger btn-sm remove-from-cart"><i class="fas fa-trash"></i></button>

                                    </td>

                                </tr>

                            @endforeach

                        @endif

                        </tbody>

                        <tfoot>

                        <tr>

                            <td colspan="5" class="text-right"><h3><strong>Total ${{ $total }}</strong></h3></td>

                        </tr>

                        <tr>

                            <td colspan="5" class="text-right">

                                <a href="{{ url('/') }}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a>

                                <a href="{{url('/checkout')}}" class="btn btn-success">Checkout</a>

                            </td>

                        </tr>

                        </tfoot>

                    </table>
                </div>
            </div>
        </div>
    </section>




@endsection

@section('footer')
    @parent
    <!-- BEGIN PAGE LEVEL SCRIPTS -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script  src="{{asset('js/jquery-3.1.1.min.js')}}"  ></script>
    <script src="{{asset('js/bootstrap.min.js')}}"  ></script>
    <script type="text/javascript">



        $(".update-cart").change(function (e) {

            e.preventDefault();



            var ele = $(this);



            $.ajax({

                url: '{{ route('update.cart') }}',

                method: "patch",

                data: {

                    _token: '{{ csrf_token() }}',

                    id: ele.parents("tr").attr("data-id"),

                    quantity: ele.parents("tr").find(".quantity").val()

                },

                success: function (response) {

                    window.location.reload();

                }

            });

        });



        $(".remove-from-cart").click(function (e) {

            e.preventDefault();



            var ele = $(this);



            if(confirm("Are you sure want to remove?")) {

                $.ajax({

                    url: '{{ route('remove.from.cart') }}',

                    method: "DELETE",

                    data: {

                        _token: '{{ csrf_token() }}',

                        id: ele.parents("tr").attr("data-id")

                    },

                    success: function (response) {

                        window.location.reload();

                    }

                });

            }

        });

    <!-- END PAGE LEVEL SCRIPTS -->
    </script>
@endsection

  

resources/views/checkout.blade.php
@extends('layouts.main')
@section('title', 'Category')
@section('head')
    @parent
    <!--  <link rel="stylesheet" href="./style.css">-->
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <title>INSTAKTER</title>
    <script src="https://www.paypal.com/sdk/js?client-id=AU7wwFkFdvWNGEkhAGvRAOHQcShs3fkZRyIU45S7OZrDAEu594Erhb--8axPEABqnOCX6hJg5JM0ePmV&currency=USD&disable-funding=credit"></script>
{{--    <script src="https://www.paypal.com/sdk/js?client-id=AU7wwFkFdvWNGEkhAGvRAOHQcShs3fkZRyIU45S7OZrDAEu594Erhb--8axPEABqnOCX6hJg5JM0ePmV&currency=USD"></script>--}}
{{--    <script src="https://www.paypal.com/sdk/js?client-id=YOUR_ID&disable-funding=credit"></script>--}}
@endsection
@section('content')
    <br><br>
    <section class="place-order">

        <div class="container">
            <div class="row">
                <div class="col-sm-7">
                    <div class="order-box order-info">
                        <h1><span class="number-1">1</span>Your Info</h1>
                    </div>
                    <form class="px-4" id="addpage" action="{{url('create_order')}}" method="POST">
                        <label>Phone Nmber</label>
                        <input type="text" class="phone-num" id="phone_num"  placeholder="(555)-23213-231">


                        <div class="order-box">
                            <h1><span class="number-1">2</span>Your Order</h1>
                            <br>
                            <label>First Name </label>
                            <input type="text" class="first_name" id="first_name" placeholder="First Name">
                            <label>Last Name</label>
                            <input type="text" class="last_name"  id="last_name"placeholder="Last Name">
                            <label>Email</label>
                            <input type="email" class="email"     id="email"placeholder="Email">
                        </div> 
                    </form>
                    <input type="hidden" id="transaction_id">
                    <input type="hidden" id="transaction_status">
                </div>
                <div class="col-sm-5 py-5 right-box">

                    <h2>order summary</h2>
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Price</th>
                        </tr>
                        </thead>
                        <tbody>
                        @php $total = 0 @endphp

                        @if(session('cart'))

                            @foreach(session('cart') as $id => $details)
                                @php $total += $details['price'] * $details['quantity'] @endphp
                                <tr>
                                    <td>{{ $details['name'] }}</td>
                                    <td>
                                        {{-- <i class="fa fa-minus"></i> --}}
                                        <span>{{ $details['quantity'] }}</span>
                                        {{-- <i class="fa fa-plus"></i> --}}
                                    </td>
                                    <td>${{ $details['price'] }}</td>
                                </tr>

                            @endforeach

                        @endif
                        </tbody>
                    </table>


                    <table class="table sub-total-table">

                        <tbody>
                        <tr>
                            <td colspan="3">Subtotal </td>
                            <td colspan="2">${{ $total }}</td>
                        </tr>
                        {{-- <tr>
                            <td colspan="3">Taxes & Fees</td>
                            <td colspan="2">$10.8</td>
                        </tr> --}}
                        {{-- <tr>
                            <td colspan="5"><input placeholder="Promo Code" class="propmo-code"/></td>
                        </tr>
                        <tr>
                            <td>Support our team</td>
                            <td>4$</td>
                            <td>5$</td>
                            <td>8$</td>
                            <td>Custom</td>
                        </tr>
                        <tr>
                            <td colspan="5"><input placeholder="$3" class="propmo-code"/></td>
                        </tr> --}}
                        <tr>
                            <hr>
                            <td colspan="3"><h2>Grand Total</h2></td>
                            <td colspan="2"><b>${{ $total }}</b></td>
                        </tr>
                        {{-- <tr>
                            <td colspan="5"><a href="#" class="place-order">place  order</a></td>
                        </tr> --}}

                        </tbody>
                    </table>
                    <div class="order-box">
                        <h1><span class="number-1"></span>Payment</h1>
                        <br>

                        <!-- Set up a container element for the button -->
                        <div id="paypal-button-container"></div>

                    </div>

                </div>
            </div>
        </div>

    </section>
    <br>
@endsection

@section('footer')
        @parent
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        {{-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script> --}}
        <script  src="{{asset('js/jquery-3.1.1.min.js')}}"  ></script>
        <script  src="{{asset('js/popper.min.js')}}"  ></script>
        <script src="{{asset('js/bootstrap.min.js')}}"  ></script>

        <script>
            var amount = '<?php echo $total;?>';
            paypal.Buttons({

                // Sets up the transaction when a payment button is clicked
                createOrder: function(data, actions) {
                    return actions.order.create({
                        purchase_units: [{
                            amount: {
                                value: '77.44' // Can reference variables or functions. Example: `value: document.getElementById('...').value`
                            }
                        }]
                    });
                },

                // Finalize the transaction after payer approval
                onApprove: function(data, actions) {
                    return actions.order.capture().then(function(orderData) {
                        // Successful capture! For dev/demo purposes:
                        console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                        var transaction = orderData.purchase_units[0].payments.captures[0];
                        // alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');
                        $("#transaction_id").val(transaction.id);
                        $("#transaction_status").val(transaction.status);
                        createorder();
                        // When ready to go live, remove the alert and show a success message within this page. For example:
                        // var element = document.getElementById('paypal-button-container');
                        // element.innerHTML = '';
                        // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                        // Or go to another URL:  actions.redirect('thank_you.html');
                    });
                }
            }).render('#paypal-button-container');
            function  createorder()
            {
                var url = '{{url("/")}}';
                var transaction_id =   $("#transaction_id").val();
                var transaction_status = $("#transaction_status").val();

                var phone_num = $("#phone_num").val();
                var first_name = $("#first_name").val();
                var last_name = $("#last_name").val();
                var email = $("#email").val();
                $.ajax({
                    type : "post",
                    dataType : "json",
                    url : url+'/create_order',
                    data : {"_token": "{{ csrf_token() }}",
                        'transaction_id':transaction_id,
                        'transaction_status':transaction_status,
                        'phone_num':phone_num,
                        'first_name':first_name,
                        'last_name':last_name,
                        'email':email,
                    },
                    success: function(data) {
                        console.log(data);
                        if(data.code==200)
                        {
                            window.location.href=url+'/'
                        }
                    }
                })
            }

        </script>
    @endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>  

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>