routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::impersonate();

Route::get('/', function () {
//    return view('welcome');
    return view('coming-soon');
});

Route::get('/test', function () {
//    return view('welcome');
    return view('productlisting');
});




Route::get('cart', [\App\Http\Controllers\AdminDashboardController::class, 'cart'])->name('cart');

Route::get('add-to-cart/{id}', [\App\Http\Controllers\AdminDashboardController::class, 'addToCart'])->name('add.to.cart');

Route::Post('add-to-cart', [\App\Http\Controllers\AdminDashboardController::class, 'addToCartAjax'])->name('add.to.carts');

Route::patch('update-cart', [\App\Http\Controllers\AdminDashboardController::class, 'updateCart'])->name('update.cart');

Route::delete('remove-from-cart', [\App\Http\Controllers\AdminDashboardController::class, 'removeCart'])->name('remove.from.cart');

Route::get('checkout', [\App\Http\Controllers\AdminDashboardController::class, 'checkout']);
Route::post('create_order', [\App\Http\Controllers\ClubController::class, 'createOrder']);


Route::get('INSTAKTER', [\App\Http\Controllers\AdminDashboardController::class, 'productsVendor'])->name('productsVendor');

Route::get('INSTAKTER/{id}', [\App\Http\Controllers\AdminDashboardController::class, 'vendorLists'])->name('vendorLists');

Route::get('INSTAKTER/{id}/{categoryid}',[\App\Http\Controllers\AdminDashboardController::class, 'vendorLists2'])->name('vendorLists2');

Route::POST('productData', [\App\Http\Controllers\AdminDashboardController::class, 'productData'])->name('productData');
 
//Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//    return view('dashboard');
//})->name('dashboard');

//Route::middleware(['auth:sanctum', 'verified'])->group(['prefix' => 'admin'], function () {
//    Route::get('/', [\App\Http\Controllers\AdminDashboardController::class, 'index'])->name('admin');
//});

    Route::group(['middleware' => 'auth:admin', 'prefix'=> 'admin', 'as' => 'admin.'], function() {
        Route::get('dashboard', [\App\Http\Controllers\AdminDashboardController::class, 'index'])->name('dashboard');
        Route::post('loginAsVendor', [\App\Http\Controllers\AdminDashboardController::class, 'loginAsVendor'])->name('loginAsVendor');

        Route::get('vendorsList', [\App\Http\Controllers\AdminDashboardController::class, 'vendorsList'])->name('vendorsList');

        Route::get('customersList', [\App\Http\Controllers\AdminDashboardController::class, 'customersList'])->name('customersList');


        Route::get('ordersList', [\App\Http\Controllers\AdminDashboardController::class, 'ordersList'])->name('ordersList');


        //categories
        Route::get('categories', [\App\Http\Controllers\CategoryController::class, 'categoryList'])->name('categories');
        Route::get('admin/removeCategory', [\App\Http\Controllers\CategoryController::class, 'removeCategory'])->name('removeCategory');
        Route::get('admin/editCategory', [\App\Http\Controllers\CategoryController::class, 'showCategory'])->name('editCategory');
        Route::post('Category', [\App\Http\Controllers\CategoryController::class, 'storeCategory'])->name('Category');



        //   Route::get('productsList/{id?}', [\App\Http\Controllers\AdminDashboardController::class, 'productsList'])->name('productsList');
        Route::get('productsList', [\App\Http\Controllers\AdminDashboardController::class, 'productsList'])->name('productsList');
        Route::get('productsCreate', [\App\Http\Controllers\AdminDashboardController::class, 'productsCreate'])->name('productsCreate');
        Route::post('productADD', [\App\Http\Controllers\AdminDashboardController::class, 'productADD'])->name('productADD');
        Route::get('productView/{id}', [\App\Http\Controllers\AdminDashboardController::class, 'productView'])->name('productView');
        Route::post('productUpdate', [\App\Http\Controllers\AdminDashboardController::class, 'productUpdate'])->name('productUpdate');
        Route::post('productDelete', [\App\Http\Controllers\AdminDashboardController::class, 'productDelete'])->name('productDelete');

        Route::get('delProducts', [\App\Http\Controllers\AdminDashboardController::class, 'Removeproducts'])->name('DelProducts');

        Route::get('CategoryList', [\App\Http\Controllers\AdminDashboardController::class, 'categoryList'])->name('CategoryList');
        Route::get('removeCategory', [\App\Http\Controllers\AdminDashboardController::class, 'removeCategory'])->name('removeCategory');
        Route::get('editCategory', [\App\Http\Controllers\AdminDashboardController::class, 'showCategory'])->name('editCategory');
        Route::post('AddCategory', [\App\Http\Controllers\AdminDashboardController::class, 'storeCategory'])->name('AddCategory');

        Route::get('AdminProfile', [\App\Http\Controllers\AdminDashboardController::class, 'adminProfile'])->name('AdminProfile');
        Route::post('AdminProfileUpdate', [\App\Http\Controllers\AdminDashboardController::class, 'adminProfileUpdate'])->name('AdminProfileUpdate');

      //  Route::get('viewWidgets/{id?}', [\App\Http\Controllers\AdminDashboardController::class, 'viewWidgets'])->name('viewWidgets');
        Route::get('viewWidgets', [\App\Http\Controllers\AdminDashboardController::class, 'viewWidgets'])->name('viewWidgets');

     //   Route::get('viewMemberships/{id?}', [\App\Http\Controllers\AdminDashboardController::class, 'viewMemberships'])->name('viewMemberships');
        Route::get('viewMemberships', [\App\Http\Controllers\AdminDashboardController::class, 'viewMemberships'])->name('viewMemberships');

        Route::resource('defaultWidget', \App\Http\Controllers\DefaultWidgetController::class);

        Route::resource('defaultMemberships', \App\Http\Controllers\DefaultSubscriptionController::class);


    });



    Route::group(['middleware' => ['auth:vendor']], function() {

        Route::get('vendor/dashboard', [App\Http\Controllers\VendorDashboardController::class , 'index'])->name('vendor.dashboard');
        Route::resource('customers', \App\Http\Controllers\CustomersController::class);

        Route::resource('orders', \App\Http\Controllers\OrdersController::class);
        Route::resource('widget', \App\Http\Controllers\WidgetController::class);
        Route::resource('membership', \App\Http\Controllers\SubscriptionController::class);
        Route::resource('vendor', \App\Http\Controllers\VendorsController::class);
        Route::resource('products', \App\Http\Controllers\ProductsController::class);
        Route::get('updateSettings', [\App\Http\Controllers\VendorsController::class, 'updateSettings'])->name('updateSettings');
        Route::post('updateVendorSettings', [\App\Http\Controllers\VendorsController::class, 'updateVendorSettings'])->name('updateVendorSettings');

        Route::get('pluginSetting', [\App\Http\Controllers\VendorsController::class, 'pluginSetting']);
        Route::get('updateAccessToken/{id}', [\App\Http\Controllers\VendorsController::class, 'updateAccessToken']);
        Route::resource('myclub', \App\Http\Controllers\ClubController::class);

        Route::get('clubDetails', [\App\Http\Controllers\ClubController::class, 'index'])->name('ClubListing');



        //products vendor
        Route::resource('products', \App\Http\Controllers\ProductsController::class);
        Route::post('products/{product}', [\App\Http\Controllers\ProductsController::class, 'update'])->name('products.update');


        Route::get('customerDetails', [\App\Http\Controllers\CustomersController::class, 'index'])->name('CustomerListing');
        Route::get('customers/{id}', [\App\Http\Controllers\CustomersController::class, 'show'])->name('customers.view');

        Route::get('orderDetails', [\App\Http\Controllers\OrdersController::class, 'index'])->name('OrderListing');
        Route::get('orders/{id}', [\App\Http\Controllers\OrdersController::class, 'show'])->name('orders.view');




        Route::get('myclub/delete/{id}',[ \App\Http\Controllers\ClubController::class,'destroy']);
    });



Route::get('/admin/login', [\App\Http\Controllers\Auth\LoginController::class, 'showAdminLoginForm'])->name('admin/login');
Route::post('/admin/login', [\App\Http\Controllers\Auth\LoginController::class, 'userLogin'])->name('admin/login');
Route::post('/admin/logout', [\App\Http\Controllers\Auth\LogoutController::class, 'userLogout'])->name('admin/logout');


Route::get('/login', [\App\Http\Controllers\Auth\LoginController::class,'showVendorLogin'])->name('login');
Route::post('/login', [\App\Http\Controllers\Auth\LoginController::class,'vendorLogin'])->name('login');

Route::post('/registervendor', [\App\Http\Controllers\Auth\RegisterController::class,'registerVendor'])->name('registervendor');

Route::get('logout',[App\Http\Controllers\Auth\LogoutController::class , 'userLogout'])->name('logout');

resources/views/admin/categories.blade.php
@extends('layouts.admin')
@section('title', 'Dashboard')

@section('head')
    @parent



    <link rel="stylesheet" type="text/css"
          href="{{ asset('vendor-dashboard/plugins/table/datatable/datatables.css') }}">
    <link rel="stylesheet" type="text/css"
          href="{{ asset('vendor-dashboard/plugins/table/datatable/custom_dt_miscellaneous.css') }}">
    <link rel="stylesheet" type="text/css"
          href="{{ asset('vendor-dashboard/assets/css/forms/theme-checkbox-radio.css') }}">
    <link rel="stylesheet" type="text/css"
          href="{{ asset('vendor-dashboard/plugins/table/datatable/dt-global_style.css') }}">
@endsection
@section('page-title', 'My Clubs')
@section('content')
    <div class="col-lg-12">
        <div class="statbox widget box box-shadow">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-6 col-md-6 col-sm-6 col-6">
                        <h4>Categories List</h4>

                    </div>

                    <div class="col-xl-6 col-md-6 col-sm-6 col-6" style="text-align: right;margin-top: 10px;">
                        <button type="button" class="btn btn-outline-primary" id="addCategory">Add Category</button>
                        <!--                        { { url('myclub/create')}}-->
                    </div>


                </div>
                @if(session()->has('message'))
                    <div class="alert alert-success mb-4" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                 fill="none"
                                 stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                 stroke-linejoin="round"
                                 class="feather feather-x close" data-dismiss="alert">
                                <line x1="18" y1="6" x2="6" y2="18"></line>
                                <line x1="6" y1="6" x2="18" y2="18"></line>
                            </svg>
                        </button>
                        {{ session()->get('message') }}</button>
                    </div>
                @endif

            </div>
        </div>
        <div class="widget-content widget-content-area">
            <div class="table-responsive mb-4">
                <div class="table-responsive mb-4">
                    <table id="vendor_categories_dt" class="table table-bordered"
                           style="width:100%;">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Category Title</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>



    <div id="categoryModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <form method="post" id="category_form">
                    <div class="modal-header">
                        <h4 class="modal-title text-left" style="margin-left:0;">Add Category</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>

                    </div>
                    <div class="modal-body">
                        {{csrf_field()}}
                        <span id="form_output"></span>
                        <div class="form-group">
                            <label>Category Tilte</label>
                            <input type="text" name="category_title" id="category_title" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label>Category Slug</label>
                            <input type="text" name="category_slug" id="category_slug" class="form-control"/>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input type="hidden" name="category_id" id="category_id" value="">
                        <input type="hidden" name="button_action" id="button_action" value="insert"/>
                        <input type="submit" name="submit" id="action" value="Add" class="btn btn-info"/>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection



@section('footer')
    @parent
    <!-- BEGIN PAGE LEVEL SCRIPTS -->

    <script src="{{asset('vendor-dashboard/plugins/sweetalerts/promise-polyfill.js')}}"></script>
    <script src="{{asset('vendor-dashboard/plugins/table/datatable/datatables.js')}}"></script>
    <script src="{{asset('vendor-dashboard/plugins/table/datatable/custom_miscellaneous.js')}}"></script>

    <!-- END PAGE LEVEL SCRIPTS -->

    <script src="{{asset('vendor-dashboard/plugins/table/datatable/datatables.js')}}"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            var table = $('#vendor_categories_dt').DataTable({

                //orderCellsTop: true,
                fixedHeader: true,
                processing: true,
                serverSide: true,
                ajax: "{{route('admin.categories')}}",
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'categoryTitle', name: 'categoryTitle'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ],
                columnDefs: [
                    {"targets": 0, "width": "70px", "className": "ta-c"},
                    {"targets": 1, "width": "120px", "className": "ta-c"},
                    {"targets": 2, "width": "100px", "className": "ta-c"}
                ]
            });

            // $('.filter-select').change(function () {
            //     table.columns($(this).data('column'))
            //         .search($(this).val())
            //         .draw();
            // });


        });

        $('#addCategory').click(function () {
            $('#categoryModal').modal('show');
            $('#category_form')[0].reset();
            $('#form_output').html('');
            $('#button_action').val('insert');
            $('#action').val('Add');
        });

        $('#category_form').on('submit', function (event) {
            event.preventDefault();
            var form_data = $(this).serialize();
            $.ajax({
                url: "{{ route('admin.Category') }}",
                method: "POST",
                data: form_data,
                dataType: "json",
                success: function (data) {
                    if (data.error.length > 0) {
                        var error_html = '';
                        for (var count = 0; count < data.error.length; count++) {
                            error_html += '<div class="alert alert-danger">' + data.error[count] + '</div>';
                        }
                        $('#form_output').html(error_html);
                    } else {
                        $('#form_output').html(data.success);


                        $('#category_form')[0].reset();
                        $('#action').val('Add');
                        $('.modal-title').text('Add Data');
                        $('#button_action').val('insert');
                        $('#vendor_categories_dt').DataTable().ajax.reload();

                        // $('#categoryModal').modal('hide');
                        $('.btn-default').click();
                        toastr.success('Category added Succesfully', {timeOut: 5000});
                    }
                }
            })
        });


        $(document).on('click', '.edit', function () {
            var id = $(this).attr("id");
            $('#form_output').html('');
            $.ajax({
                url: "{{route('admin.editCategory')}}",
                method: 'get',
                data: {id: id},
                dataType: 'json',
                success: function (data) {
                    $('#category_title').val(data.categoryTitle);
                    $('#category_slug').val(data.categorySlug);
                    console.log(id);
                    $('#category_id').val(id);
                    $('#categoryModal').modal('show');
                    $('#action').val('Edit');
                    $('.modal-title').text('Edit Data');
                    $('#button_action').val('update');
                }
            })
        });

        $(document).on('click', '.delete', function () {
            var id = $(this).attr('id');


            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Delete',
                padding: '1em'
            }).then(function (result) {
                if (result.value)
                {

                    $.ajax({
                        url: "{{route('admin.removeCategory')}}",
                        mehtod: "get",
                        data: {id: id},
                        success: function (data) {
                            // alert(data);
                            swal(
                                'Deleted!',
                                'Your file has been deleted.',
                                'success'
                            );
                            //$('#club-table').DataTable().ajax.reload();
                            toastr.success('Category deleted Succesfully', {timeOut: 5000});
                            $('#vendor_categories_dt').DataTable().ajax.reload();
                        }
                    });
                }
            });

        });


    </script>

@endsection
<!-- BEGIN PAGE LEVEL SCRIPTS -->

resources/views/admin/default_subscriptions.blade.php
@extends('layouts.admin')
@section('title', 'Dashboard')

@section('head')
    @parent
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="{{asset('admin-dashboard/assets/css/forms/switches.css')}}">
    <link href="{{ asset('admin-dashboard/plugins/pricing-table/css/component.css')}}" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL STYLES -->
@endsection
@section('content')
    <div class="col-lg-12 layout-spacing">
        <div class="statbox widget box box-shadow">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Membership Settings</h4>
                    </div>
                </div>
            </div>
            <div class="widget-content widget-content-area">
                <div class="container p-0">
                    <section class="pricing-section bg-7  mt-1">
                        <div class="pricing pricing--norbu  m-0">
                            @foreach($plans as $key=>$plan)
                                <div class="pricing__item mr-2 m-0">
                                    <form method="POST" action="{{route('admin.defaultMemberships.update', $defaultPlans[$key]->id)}}">
                                        @method('PUT')
                                        @csrf
                                        <h3 class="pricing__title">{{ \Illuminate\Support\Str::upper($defaultPlans[$key]->level) }}</h3>
                                        <p class="pricing__sentence"><textarea rows="3" name="description" class="form-control">{{$defaultPlans[$key]->description}}</textarea></p>
                                        <div class="pricing__price">
                                            <input type="hidden" name="price" value="{{number_format($plan->amount / 100, 2)}}">
                                            <input type="hidden" name="period" value="{{$plan->interval}}">
                                            <span class="pricing__currency">{{$plan->currency}}</span>{{number_format($plan->amount / 100, 2)}}<span class="pricing__period">/ {{ $plan->interval }}</span>
                                        </div>

                                        <p class="pricing__sentence">
                                            <label for="features">Features (Comma Separated)</label>
                                            <textarea rows="6" name="features" class="form-control">{{$defaultPlans[$key]->features}}</textarea>
                                        </p>
                                        <button type="submit" class="pricing__action mx-auto mb-4">Update</button>
                                    </form>
                                </div>
                            @endforeach
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/productsCreate.blade.php
@extends('layouts.admin')
@section('title', 'Dashboard')
@section('head')
    @parent
    <link rel="stylesheet" type="text/css" href="{{ asset('admin-dashboard/plugins/table/datatable/datatables.css') }}">
    <link rel="stylesheet" type="text/css"
          href="{{ asset('admin-dashboard/plugins/table/datatable/custom_dt_miscellaneous.css') }}">
    <link rel="stylesheet" type="text/css"
          href="{{ asset('admin-dashboard/assets/css/forms/theme-checkbox-radio.css') }}">
    <link rel="stylesheet" type="text/css"
          href="{{ asset('admin-dashboard/plugins/table/datatable/dt-global_style.css') }}">
@endsection
@section('content')
    <div class="col-lg-12">
        <div class="statbox widget box box-shadow">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Add Product</h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="widget-content widget-content-area">
            <h1>
                Product Information
            </h1>
            @if(isset($output['id']) && !empty($output['id']))

                <form method="post" action="{{route('admin.productUpdate')}}" enctype="multipart/form-data">
                    <input type="hidden" name="id" value="{{$output['id']}}">
            @else
                <form method="post" action="{{route('admin.productADD')}}" enctype="multipart/form-data">
            @endif


                {{ csrf_field() }}
                <div class="row">
                    <div class="col-md-6">
                        <div class="col-md-12">

                            <div class="form-group">
                                <label for="title">Product Title</label>
                                <input type="text" name="title" class="form-control" id="" value="{{old('title', $output['title'])}}"
                                       placeholder="Enter Product Title">

                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="short_description">Product Category</label>
                                <select class="form-control form-small" name="category_id">
                                    @foreach($Categories as $category)
                                        <option value="{{$category->id}}">{{$category->categoryTitle}}</option>
                                    @endforeach

                                </select>

                            </div>
                        </div>


                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="price">Product Price</label>
                                <input type="number" name="price" class="form-control" id="" value="{{old('price', $output['price'])}}"
                                       placeholder="Enter Product Price">
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="price">Product Quantity</label>
                                <input type="number" name="quantity" class="form-control" id="" value="{{old('quantity', $output['quantity'])}}"
                                       placeholder="Enter Product Quantity">
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="status">Product Status</label>


                                <select class="form-control form-small" name="status">

                                    <option >Select Product Status</option>
                                    <option value="1" {{$output['status'] == 1 ? 'selected=selected' : ''}} >Active</option>
                                    <option value="0" {{$output['status'] == 0 ? 'selected=selected' : ''}}>IN-Active</option>
                                </select>

                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="short_description">Product Short Description</label>
                                <input type="text" name="short_description" class="form-control" id="" value="{{old('short_description', $output['short_description'])}}"
                                       placeholder="Enter Product Short Description">

                            </div>
                        </div>



                    </div>

                    <div class="col-md-6">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="description">Product Description</label>
                                <textarea class="form-control" name="description">{{old('description', $output['description'])}}</textarea>

                            </div>
                        </div>


                        <div class="col-md-12">
                            <div class=" custom-file-container" data-upload-id="myFirstImage">
                                <label>Upload (Single File) <a href="javascript:void(0)"
                                                               class="custom-file-container__image-clear"
                                                               title="Clear Image">x</a></label>
                                <label class="custom-file-container__custom-file">
                                    <input type="file" name="image_url"
                                           class="custom-file-container__custom-file__custom-file-input"
                                           accept="image/*">
                                    <input type="hidden" name="MAX_FILE_SIZE" value="10485760"/>
                                    <span class="custom-file-container__custom-file__custom-file-control"></span>
                                </label>
                                @if(isset($output['image_url']) && $output['image_url'] != '')
                                    <style>
                                        .custom-file-container__image-preview {
                                            ox-sizing: border-box;
                                            transition: all 0.2s ease;
                                            margin-top: 54px;
                                            margin-bottom: 40px;
                                            height: 250px;
                                            width: 100%;
                                            border-radius: 4px;
                                            background-size: contain;
                                            background-position: center center;
                                            background-repeat: no-repeat;
                                            background-color: #fff;
                                            overflow: auto;
                                            padding: 15px;
                                        }
                                    </style>
                                    <!--                                    div m backgroud image lagae gy tu ok ho jae gaa kaam -->
                                    <img class="custom-file-container__image-preview" style="  margin-top: 54px;
                                        overflow: auto;
                                                padding: 15px;
                                                margin-bottom: 40px;
                                                height: 250px;
                                                width: 100%;
                                                border-radius: 4px;" src="{{asset($output['image_url'] ?? '')}}">
                                @else
                                    <div class="custom-file-container__image-preview"></div>
                                @endif


                            </div>
                        </div>

                    </div>


                </div>


                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    </div>
@endsection

@section('footer')
    @parent
    <script>
        //First upload
        var firstUpload = new FileUploadWithPreview('myFirstImage')
    </script>
    <script>
        var formSmall = $(".form-small").select2({tags: true});
        formSmall.data('select2').$container.addClass('form-control-sm')
    </script>
@endsection