routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::impersonate();

Route::get('/', function () {
//    return view('welcome');
    return view('coming-soon');
});

Route::get('/test', function () {
//    return view('welcome');
    return view('productlisting');
});




Route::get('cart', [\App\Http\Controllers\AdminDashboardController::class, 'cart'])->name('cart');

Route::get('add-to-cart/{id}', [\App\Http\Controllers\AdminDashboardController::class, 'addToCart'])->name('add.to.cart');

Route::Post('add-to-cart', [\App\Http\Controllers\AdminDashboardController::class, 'addToCartAjax'])->name('add.to.carts');

Route::patch('update-cart', [\App\Http\Controllers\AdminDashboardController::class, 'updateCart'])->name('update.cart');

Route::delete('remove-from-cart', [\App\Http\Controllers\AdminDashboardController::class, 'removeCart'])->name('remove.from.cart');

Route::get('checkout', [\App\Http\Controllers\AdminDashboardController::class, 'checkout']);
Route::post('create_order', [\App\Http\Controllers\ClubController::class, 'createOrder']);


Route::get('INSTAKTER', [\App\Http\Controllers\AdminDashboardController::class, 'productsVendor'])->name('productsVendor');

Route::get('INSTAKTER/{id}', [\App\Http\Controllers\AdminDashboardController::class, 'vendorLists'])->name('vendorLists');

Route::get('INSTAKTER/{id}/{categoryid}',[\App\Http\Controllers\AdminDashboardController::class, 'vendorLists2'])->name('vendorLists2');

Route::POST('productData', [\App\Http\Controllers\AdminDashboardController::class, 'productData'])->name('productData');
 
//Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//    return view('dashboard');
//})->name('dashboard');

//Route::middleware(['auth:sanctum', 'verified'])->group(['prefix' => 'admin'], function () {
//    Route::get('/', [\App\Http\Controllers\AdminDashboardController::class, 'index'])->name('admin');
//});

    Route::group(['middleware' => 'auth:admin', 'prefix'=> 'admin', 'as' => 'admin.'], function() {
        Route::get('dashboard', [\App\Http\Controllers\AdminDashboardController::class, 'index'])->name('dashboard');
        Route::post('loginAsVendor', [\App\Http\Controllers\AdminDashboardController::class, 'loginAsVendor'])->name('loginAsVendor');

        Route::get('vendorsList', [\App\Http\Controllers\AdminDashboardController::class, 'vendorsList'])->name('vendorsList');

        Route::get('customersList', [\App\Http\Controllers\AdminDashboardController::class, 'customersList'])->name('customersList');


        Route::get('ordersList', [\App\Http\Controllers\AdminDashboardController::class, 'ordersList'])->name('ordersList');


        //categories
        Route::get('categories', [\App\Http\Controllers\CategoryController::class, 'categoryList'])->name('categories');
        Route::get('admin/removeCategory', [\App\Http\Controllers\CategoryController::class, 'removeCategory'])->name('removeCategory');
        Route::get('admin/editCategory', [\App\Http\Controllers\CategoryController::class, 'showCategory'])->name('editCategory');
        Route::post('Category', [\App\Http\Controllers\CategoryController::class, 'storeCategory'])->name('Category');



        //   Route::get('productsList/{id?}', [\App\Http\Controllers\AdminDashboardController::class, 'productsList'])->name('productsList');
        Route::get('productsList', [\App\Http\Controllers\AdminDashboardController::class, 'productsList'])->name('productsList');
        Route::get('productsCreate', [\App\Http\Controllers\AdminDashboardController::class, 'productsCreate'])->name('productsCreate');
        Route::post('productADD', [\App\Http\Controllers\AdminDashboardController::class, 'productADD'])->name('productADD');
        Route::get('productView/{id}', [\App\Http\Controllers\AdminDashboardController::class, 'productView'])->name('productView');
        Route::post('productUpdate', [\App\Http\Controllers\AdminDashboardController::class, 'productUpdate'])->name('productUpdate');
        Route::post('productDelete', [\App\Http\Controllers\AdminDashboardController::class, 'productDelete'])->name('productDelete');

        Route::get('delProducts', [\App\Http\Controllers\AdminDashboardController::class, 'Removeproducts'])->name('DelProducts');

        Route::get('CategoryList', [\App\Http\Controllers\AdminDashboardController::class, 'categoryList'])->name('CategoryList');
        Route::get('removeCategory', [\App\Http\Controllers\AdminDashboardController::class, 'removeCategory'])->name('removeCategory');
        Route::get('editCategory', [\App\Http\Controllers\AdminDashboardController::class, 'showCategory'])->name('editCategory');
        Route::post('AddCategory', [\App\Http\Controllers\AdminDashboardController::class, 'storeCategory'])->name('AddCategory');

        Route::get('AdminProfile', [\App\Http\Controllers\AdminDashboardController::class, 'adminProfile'])->name('AdminProfile');
        Route::post('AdminProfileUpdate', [\App\Http\Controllers\AdminDashboardController::class, 'adminProfileUpdate'])->name('AdminProfileUpdate');

      //  Route::get('viewWidgets/{id?}', [\App\Http\Controllers\AdminDashboardController::class, 'viewWidgets'])->name('viewWidgets');
        Route::get('viewWidgets', [\App\Http\Controllers\AdminDashboardController::class, 'viewWidgets'])->name('viewWidgets');

     //   Route::get('viewMemberships/{id?}', [\App\Http\Controllers\AdminDashboardController::class, 'viewMemberships'])->name('viewMemberships');
        Route::get('viewMemberships', [\App\Http\Controllers\AdminDashboardController::class, 'viewMemberships'])->name('viewMemberships');

        Route::resource('defaultWidget', \App\Http\Controllers\DefaultWidgetController::class);

        Route::resource('defaultMemberships', \App\Http\Controllers\DefaultSubscriptionController::class);


    });



    Route::group(['middleware' => ['auth:vendor']], function() {

        Route::get('vendor/dashboard', [App\Http\Controllers\VendorDashboardController::class , 'index'])->name('vendor.dashboard');
        Route::resource('customers', \App\Http\Controllers\CustomersController::class);

        Route::resource('orders', \App\Http\Controllers\OrdersController::class);
        Route::resource('widget', \App\Http\Controllers\WidgetController::class);
        Route::resource('membership', \App\Http\Controllers\SubscriptionController::class);
        Route::resource('vendor', \App\Http\Controllers\VendorsController::class);
        Route::resource('products', \App\Http\Controllers\ProductsController::class);
        Route::get('updateSettings', [\App\Http\Controllers\VendorsController::class, 'updateSettings'])->name('updateSettings');
        Route::post('updateVendorSettings', [\App\Http\Controllers\VendorsController::class, 'updateVendorSettings'])->name('updateVendorSettings');

        Route::get('pluginSetting', [\App\Http\Controllers\VendorsController::class, 'pluginSetting']);
        Route::get('updateAccessToken/{id}', [\App\Http\Controllers\VendorsController::class, 'updateAccessToken']);
        Route::resource('myclub', \App\Http\Controllers\ClubController::class);

        Route::get('clubDetails', [\App\Http\Controllers\ClubController::class, 'index'])->name('ClubListing');



        //products vendor
        Route::resource('products', \App\Http\Controllers\ProductsController::class);
        Route::post('products/{product}', [\App\Http\Controllers\ProductsController::class, 'update'])->name('products.update');


        Route::get('customerDetails', [\App\Http\Controllers\CustomersController::class, 'index'])->name('CustomerListing');
        Route::get('customers/{id}', [\App\Http\Controllers\CustomersController::class, 'show'])->name('customers.view');

        Route::get('orderDetails', [\App\Http\Controllers\OrdersController::class, 'index'])->name('OrderListing');
        Route::get('orders/{id}', [\App\Http\Controllers\OrdersController::class, 'show'])->name('orders.view');




        Route::get('myclub/delete/{id}',[ \App\Http\Controllers\ClubController::class,'destroy']);
    });



Route::get('/admin/login', [\App\Http\Controllers\Auth\LoginController::class, 'showAdminLoginForm'])->name('admin/login');
Route::post('/admin/login', [\App\Http\Controllers\Auth\LoginController::class, 'userLogin'])->name('admin/login');
Route::post('/admin/logout', [\App\Http\Controllers\Auth\LogoutController::class, 'userLogout'])->name('admin/logout');


Route::get('/login', [\App\Http\Controllers\Auth\LoginController::class,'showVendorLogin'])->name('login');
Route::post('/login', [\App\Http\Controllers\Auth\LoginController::class,'vendorLogin'])->name('login');

Route::post('/registervendor', [\App\Http\Controllers\Auth\RegisterController::class,'registerVendor'])->name('registervendor');

Route::get('logout',[App\Http\Controllers\Auth\LogoutController::class , 'userLogout'])->name('logout');

resources/views/admin/includes/footer.blade.php
<!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
<script src="{{ asset('js/jquery-3.1.1.min.js') }}"></script>
<script src="{{ asset('js/popper.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<script src="{{ asset('admin-dashboard/assets/js/loader.js') }}"></script>

<script src="{{ asset('admin-dashboard/plugins/perfect-scrollbar/perfect-scrollbar.min.js') }}"></script>
<script src="{{ asset('admin-dashboard/assets/js/app.js') }}"></script>
<script>
    $(document).ready(function() {
        App.init();
    });
</script>
<script src="{{ asset('admin-dashboard/assets/js/custom.js') }}"></script>
<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->
<script src="{{ asset('admin-dashboard/plugins/apex/apexcharts.min.js') }}"></script>
<script src="{{ asset('admin-dashboard/assets/js/dashboard/dash_2.js') }}"></script>

<script src="{{ asset('toastr/toastr.min.js') }}"></script>
<script src="{{asset('vendor-dashboard/plugins/sweetalerts/sweetalert2.min.js')}}"></script>
<script src="{{asset('vendor-dashboard/plugins/sweetalerts/custom-sweetalert.js')}}"></script>
<script src="{{asset('assets/js/bootstrap-select.min.js')}}"></script>
<script src="{{asset('assets/js/file-upload-with-preview.min.js')}}"></script>
<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->

<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{asset('assets/js/highlight.pack.js')}}"></script>
<script src="{{asset('assets/js/scrollspyNav.js')}}"></script>
<script src="{{asset('assets/js/jquery.steps.min.js')}}"></script>
<!--<script src="{ {asset('assets/js/custom-jquery.steps.js')}}"></script>-->
<!-- END PAGE LEVEL SCRIPTS -->        <!-- BEGIN PAGE LEVEL SCRIPTS -->

resources/views/admin/includes/head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>{{ config('app.name', 'Laravel') }} | @yield('title')</title>

<link rel="icon" type="image/x-icon" href="{{ asset('admin-dashboard/assets/img/favicon.ico') }}"/>
<link href="{{ asset('admin-dashboard/assets/css/loader.css') }}" rel="stylesheet" type="text/css"/>

<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">
<link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet" type="text/css"/>
<link href="{{ asset('admin-dashboard/assets/css/plugins.css') }}" rel="stylesheet" type="text/css"/>
<!-- END GLOBAL MANDATORY STYLES -->

<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM STYLES -->
<link href="{{ asset('assets/css/bootstrap-select.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/css/file-upload-with-preview.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('admin-dashboard/plugins/apex/apexcharts.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('admin-dashboard/assets/css/dashboard/dash_2.css') }}" rel="stylesheet" type="text/css"/>
<link href="{{ asset('admin-dashboard/assets/css/custom.css') }}" rel="stylesheet" type="text/css"/>
<link href="{{ asset('toastr/toastr.min.css') }}" rel="stylesheet" type="text/css"/>
<link href="{{asset('vendor-dashboard/plugins/sweetalerts/sweetalert2.min.css')}}" rel="stylesheet"  type="text/css"/>
<link href="{{asset('vendor-dashboard/assets/css/components/custom-sweetalert.css')}}" rel="stylesheet" type="text/css"/>

<!--  BEGIN CUSTOM STYLE FILE  -->
<link href="{{ asset('assets/css/scrollspyNav.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/jquery.steps.css') }}">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/switches.css')}}">

<link href="{{asset('assets/css/structure.css')}}" rel="stylesheet" type="text/css" class="structure" />



<style>
.swal2-icon.swal2-warning {
align-items: center;
width: 100px;
height: 100px;
margin: 20px;
}

.swal2-icon-text {
font-size: 100px !important;
}
</style>

resources/views/admin/includes/sidebar.blade.php
<!--  BEGIN SIDEBAR  -->
<div class="sidebar-wrapper sidebar-theme">
    <nav id="sidebar">
        <div class="shadow-bottom"></div>
        <ul class="list-unstyled menu-categories" id="accordionExample">
            <li class="menu">
                <a href="{{route('admin.dashboard')}}" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
<!--                        <span>Analytics</span>-->
                        <span>Dashboard</span>
                    </div>
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </div>
                </a>
            </li>
            <li class="menu">
                <a href="{{ route('admin.vendorsList') }}" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                        <span>Vendors</span>
                    </div>
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </div>
                </a>
            </li>
<!--            <li class="menu">
                <a href="{ { route('admin.categories') }}" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                        <span>Categories</span>
                    </div>
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </div>
                </a>
            </li>-->
            <li class="menu">
                <a href="{{ route('admin.customersList') }}"class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                        <span>Customers</span>
                    </div>
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </div>
                </a>
            </li>
            <li class="menu">
                <a href="{{ route('admin.ordersList') }}" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                        <span>Orders</span>
                    </div>
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </div>
                </a>
            </li>
            <li class="menu">
                <a href="{{ route('admin.productsList') }}" class="dropdown-toggle">
                    <div class="">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd"><path d="M11.5 23l-8.5-4.535v-3.953l5.4 3.122 3.1-3.406v8.772zm1-.001v-8.806l3.162 3.343 5.338-2.958v3.887l-8.5 4.534zm-10.339-10.125l-2.161-1.244 3-3.302-3-2.823 8.718-4.505 3.215 2.385 3.325-2.385 8.742 4.561-2.995 2.771 2.995 3.443-2.242 1.241v-.001l-5.903 3.27-3.348-3.541 7.416-3.962-7.922-4.372-7.923 4.372 7.422 3.937v.024l-3.297 3.622-5.203-3.008-.16-.092-.679-.393v.002z"/></svg>
                        <span>Products</span>
                    </div>
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </div>
                </a>
            </li>

{{--            <li class="menu">--}}
{{--                <a href="{{ route('admin.viewWidgets') }}" class="dropdown-toggle">--}}
{{--                    <div class="">--}}
{{--                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-airplay"><path d="M5 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-1"></path><polygon points="12 15 17 21 7 21 12 15"></polygon></svg>--}}
{{--                        <span>Widgets</span>--}}
{{--                    </div>--}}
{{--                    <div>--}}
{{--                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>--}}
{{--                    </div>--}}
{{--                </a>--}}
{{--            </li>--}}

{{--            <li class="menu">--}}
{{--                <a href="{{ route('admin.viewMemberships') }}" class="dropdown-toggle">--}}
{{--                    <div class="">--}}
{{--                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-cpu"><rect x="4" y="4" width="16" height="16" rx="2" ry="2"></rect><rect x="9" y="9" width="6" height="6"></rect><line x1="9" y1="1" x2="9" y2="4"></line><line x1="15" y1="1" x2="15" y2="4"></line><line x1="9" y1="20" x2="9" y2="23"></line><line x1="15" y1="20" x2="15" y2="23"></line><line x1="20" y1="9" x2="23" y2="9"></line><line x1="20" y1="14" x2="23" y2="14"></line><line x1="1" y1="9" x2="4" y2="9"></line><line x1="1" y1="14" x2="4" y2="14"></line></svg>--}}
{{--                        <span>Memberships</span>--}}
{{--                    </div>--}}
{{--                    <div>--}}
{{--                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>--}}
{{--                    </div>--}}
{{--                </a>--}}
{{--            </li>--}}



            <li class="menu">
                <a href="#settings" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-settings"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>
                        <span>Settings</span>
                    </div>
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down"><polyline points="6 9 12 15 18 9"></polyline></svg>
                    </div>
                </a>
                @if(\Illuminate\Support\Facades\Auth::user()->hasRole('Superadmin'))
                <ul class="collapse submenu list-unstyled" id="settings" data-parent="#accordionExample">

{{--                    <li>--}}
{{--                        <a href="{{route('admin.defaultWidget.index')}}"> Default widget </a>--}}
{{--                    </li>--}}
{{--                    <li>--}}
{{--                        <a href="{{route('admin.defaultMemberships.index')}}">Default Memberships</a>--}}
{{--                    </li>--}}

                    <li>
                        <a href="{{route('admin.AdminProfile')}}"> Users </a>
                    </li>
{{--                    <li>--}}
{{--                        <a href="{{url('/admin/roles')}}"> Roles </a>--}}
{{--                    </li>--}}
{{--                    <li>--}}
{{--                        <a href="{{url('/admin/permissions')}}"> Permissions </a>--}}
{{--                    </li>--}}
                </ul>
                @endif
            </li>
        </ul>
    </nav>
</div>
<!--  END SIDEBAR  -->